project_name: lipo
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: lipo
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/konoui/lipo/cmd.Version={{.Version}}
      - -X github.com/konoui/lipo/cmd.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format: binary

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

release:
  prerelease: auto
