name: test and release

on:
  push:

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: set up go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.x
    - name: checkout
      uses: actions/checkout@v2
    - name: lint
      run: |
        make lint
    - name: test
      run: |
        make test
  release:
    runs-on: macos-latest
    name: goreleaser
    needs: [test]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
        id: go

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
